- name: Test Connection
  hosts: nimbus

  vars_files:
    - variables.yml
    - secrets.yml

  tasks:
    - name: Ping server
      ansible.builtin.ping:
    # - name: Install tools
    #   ansible.builtin.apt:
    #     update_cache: true
    #     package:
    #       - net-tools
    #       - network-manager
    #       - vim
    #     state: present
    #   become: true
    - name: Copy VIM config to host
      ansible.builtin.copy:
        src: config-files/vimrc
        dest: ~/.vimrc
        mode: '0664' # Give read/write permissions to owner (ansible user) and corresponding group, read-only to others.
    # Configure local network
    - name: Disable cloud-init network configuration
      ansible.builtin.copy:
        src: config-files/network/99-disable-network-config.cfg
        dest: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
        mode: '0644' # Read/write to owner, read-only to group, read-only to other users
      become: true
    - name: Configure static IP addresses on local network
      ansible.builtin.template:
        src: config-files/network/01-netcfg.j2
        dest: /etc/netplan/01-netcfg.yaml
        mode: '0600' # Read/write to owner only
      become: true
      # register: result # Set "changed: true" if task makes changes. Not needed, is done implicitly by making the conditional task a handler using notify.
      notify:
        - Apply network config

  handlers:
    - import_tasks: handlers/main.yml
